TestTreeNode: treenode.h TestTreeNode.cpp
	g++ -Wall -g -std=c++11 -o TestTreeNode TestTreeNode.cpp

TestTree: treenode.h tree.h TestTree.cpp
	g++ -Wall -g -std=c++11 -o TestTree TestTree.cpp

TestTree2: treenode.h tree.h TestTree2.cpp
	g++ -Wall -g -std=c++11 -o TestTree2 TestTree2.cpp

TestTreeMap: treenode.h tree.h treemap.h TestTreeMap.cpp
	g++ -Wall -g -std=c++11 -o TestTreeMap TestTreeMap.cpp


TestTreeD:  treenode.h tree.h TestTreeD.cpp
	g++ -Wall -g -std=c++11 -o TestTreeD TestTreeD.cpp

TestTreeD2:  treenode.h tree.h TestTreeD2.cpp
	g++ -Wall -g -std=c++11 -o TestTreeD2 TestTreeD2.cpp

all: TestTreeNode TestTree TestTree2 TestTreeMap TestTreeD TestTreeD2
